# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/Documents/cpre488/Labs/MP-0/project_1/mp-0.xdc

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_0/zynq_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_0/zynq_design_1_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_2_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_0 || ORIG_REF_NAME==zynq_design_1_xbar_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_ps7_0_axi_periph_0/zynq_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_0/zynq_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_vdma_0_0/zynq_design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_vdma_0_0 || ORIG_REF_NAME==zynq_design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_v_tc_0_0/zynq_design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_v_tc_0_0 || ORIG_REF_NAME==zynq_design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_proc_sys_reset_0_0/zynq_design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlslice_0_0/zynq_design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlslice_0_0 || ORIG_REF_NAME==zynq_design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlslice_1_0/zynq_design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlslice_1_0 || ORIG_REF_NAME==zynq_design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlslice_2_0/zynq_design_1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlslice_2_0 || ORIG_REF_NAME==zynq_design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_4_0/zynq_design_1_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_4_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_4_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_snes_intf_0_1/zynq_design_1_snes_intf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_snes_intf_0_1 || ORIG_REF_NAME==zynq_design_1_snes_intf_0_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_ila_0_0/zynq_design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_ila_0_0 || ORIG_REF_NAME==zynq_design_1_ila_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_3_0/zynq_design_1_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_3_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_3_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_9/zynq_design_1_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_9 || ORIG_REF_NAME==zynq_design_1_auto_pc_9} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_0 || ORIG_REF_NAME==zynq_design_1_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_1 || ORIG_REF_NAME==zynq_design_1_auto_pc_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_2 || ORIG_REF_NAME==zynq_design_1_auto_pc_2} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_3/zynq_design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_3 || ORIG_REF_NAME==zynq_design_1_auto_pc_3} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_4/zynq_design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_4 || ORIG_REF_NAME==zynq_design_1_auto_pc_4} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_5/zynq_design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_5 || ORIG_REF_NAME==zynq_design_1_auto_pc_5} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_6/zynq_design_1_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_6 || ORIG_REF_NAME==zynq_design_1_auto_pc_6} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_7/zynq_design_1_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_7 || ORIG_REF_NAME==zynq_design_1_auto_pc_7} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_8/zynq_design_1_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_8 || ORIG_REF_NAME==zynq_design_1_auto_pc_8} -quiet] -quiet

# XDC: bd/zynq_design_1/zynq_design_1_ooc.xdc
