# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1.xci
# IP: The module: 'zynq_design_1_axi_gpio_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: U:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1.xci
# IP: The module: 'zynq_design_1_axi_gpio_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/Documents/cpre488/Labs/MP-0/project_1/project_1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
